version: '3'
services:
  sistemamf-postgres:
    image: postgres:12-alpine
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sistemamf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ronaldobrilhamuitonocorinthians123
      mem_limit: 512m
      cpu_shares: 512
    ports:
      - '5432:5432'
    networks:
      - sistemamf_internal

networks:
  sistemamf_internal:
    external:
      name: sistemamf_internal
